print("BEGIN:VCALENDAR\r")
print("VERSION:2.0\r")
print("PRODID:-//www.google.com//Python3 Generated Ical\r")
print("CALSCALE:GREGORIAN\r")
print("BEGIN:VTIMEZONE\r")
print("TZID:Asia/Almaty\r")
print("LAST-MODIFIED:20230407T050750Z\r")
print("TZURL:https://www.tzurl.org/zoneinfo-outlook/Asia/Almaty\r")
print("X-LIC-LOCATION:Asia/Almaty\r")
print("BEGIN:STANDARD\r")
print("TZNAME:+06\r")
print("TZOFFSETFROM:+0600\r")
print("TZOFFSETTO:+0600\r")
print("DTSTART:19700101T000000\r")
print("END:STANDARD\r")
print("END:VTIMEZONE\r")

import csv
with open('data.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
    for row in spamreader:
        name=row[0].strip()
        datestr=row[1].strip()

        dd=(datestr[0:2])
        mm=(datestr[3:5])
        yy=(datestr[6:10])
        # dd=int(datestr[0:2])
        # mm=int(datestr[3:5])
        # yy=int(datestr[6:10])

        print("BEGIN:VEVENT\r")
        print("DTSTAMP:20231113T075344Z\r")
        print(f"UID:5FC53010-{yy}-{mm}{dd}-BC28-1D7AE55A7C11\r")
        print(f"DTSTART;VALUE=DATE:{yy}{mm}{dd}\r")
        print(f"RRULE:FREQ=YEARLY;BYMONTH={mm};BYMONTHDAY={dd}\r")
        print(f"DTEND;VALUE=DATE:{yy}{mm}{dd}\r")
        print(f"SUMMARY:Birthday of {name}\r")
        print("URL:https://www.google.com\r")
        print(f"DESCRIPTION:День рождение {name}\r")
        print("LOCATION:Almaty\r")
        print("BEGIN:VALARM\r")
        print("ACTION:DISPLAY\r")
        print(f"DESCRIPTION:День рождение {name}\r")
        print("TRIGGER:-PT0M\r")
        print("END:VALARM\r")
        print("END:VEVENT\r")        
print("END:VCALENDAR\r")
